general {
    hide_cursor = true
    immediate_render = true
}

auth {
    pam:enabled = true
    pam:module = hyprlock

    fingerprint:enabled = true
    fingerprint:ready_message = Scan fingerprint to unlock
    fingerprint:present_message = Scanning...
    fingerprint:retry_delay = 250
}

background {
    monitor =
    path = ~/wallpaper.jpg
}

label {
    monitor =
    text = vakata
    font_family = MonoLisaCode
    font_size = 24
    font-weight = 900

    color = rgba(000000ff)

    position = 0, 35
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 450, 60
    position = 0, -50

    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.25
    rounding = 0

    outer_color = rgba(89b4faff)
    inner_color = rgba(1e1e2eff)
    font_color = rgba(cdd6f4ff)

    placeholder_text = <i>Password...</i>
    fail_text = <i>$FAIL</i>
    fade_on_empty = false
}

label {
    monitor =
    text = $FPRINTPROMPT

    font_family = MonoLisaCode
    font_size = 12
    color = rgba(a5adcbff)

    position = 0, -120
    halign = center
    valign = center
}
